add-gallery-markup
Oleksandr-Stepanyshyn/filmoteka pull request #6
Opened 2022-01-28 08:45 UTC by LanaLem

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn requested changes
Нужно исправить некоторые моменты, сделал комментарии под ними.

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/base/_container.scss
> +  width: 100%;
давай сразу поставим 480рх, что бы он тянулся от наименьшего до 480

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/base/_container.scss
> +  @media screen and (min-width: 320px) {
А вот этот медиа запрос удалим, после того как мы указали мах.ширину выше

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/templates/cardMarkup.hbs
> +<div class="film-card">
вместо `<div>`  ставим `<li>`

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/utils/_veriables.scss
> +$orange: #ff6b08;
Нужно дать более описательные названия типа: primary-text-color, accent-color,

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/utils/_fonts.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap');
шрифт я сам добавлю в head html

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/main.scss
> +@import './layout/footer';
Старайся все добавлять ближе к корневым папкам. тоесть components после components, base после base, иначе может плохо подгружаться на странице

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_films-gallery.scss
> +  grid-row-gap: 20px;
эта строка нам не нужна так как есть ширина контейнера на мобилке и падинги. Если я ошибаюсь то поправь меня

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_films-gallery.scss
> +    grid-row-gap: 30px;
а тут возможно нужно `grid-column-gap: 30px;` Мы просто учили flexbox а с grid я не особо разбираюсь

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_films-gallery.scss
> +  padding: 20px 20px 120px;
в мобилке `padding: 20px 0 40px;` либо `padding-top: 20px; padding-bottom: 40px;`

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_films-gallery.scss
> +    padding: 60px 75px 150px;
в планшете`padding: 60px 0 50px;` либо `padding-top: 60px; padding-bottom: 50px;`

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_films-gallery.scss
> +  @media screen and (min-width: 1024px) {
эту строку вообще уберем

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_film-card.scss
> +  height: 440px;
высоту лучше не указывать, должна сама определяться наполнением

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_film-card.scss
> +  max-width: 280px;
width: 100% - будет полностью на мобилке заполнять ширину контейнера

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_film-card.scss
> +    width: 294px;
max-width: calc((100%-30рх)/2);

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_film-card.scss
> +    width: 274px;
max-width: calc((100%-2x30рх)/3);

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/base/_container.scss
> -      padding-right: 70px;
padding-left: 75px;
  padding-right: 75px;

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/sass/base/_container.scss
> -      max-width: 1024px;
padding-left: 70px;
  padding-right: 70px;

2022-01-28 09:40 UTC, Oleksandr-Stepanyshyn commented on src/index.html
> +
вставляй сразу в main файл

2022-01-28 14:04 UTC, LanaLem commented on src/sass/components/_film-card.scss
> +    width: 294px;
не могу исправить, скинула скриншот в личку, почему - ломается верстка, если делать формулу под флексы

2022-01-28 14:04 UTC, LanaLem commented on src/sass/components/_film-card.scss
> +    width: 274px;
не могу исправить, скинула скриншот в личку, почему - ломается верстка, если делать формулу под флексы

2022-01-28 14:04 UTC, LanaLem commented on src/sass/base/_container.scss
> -      padding-right: 70px;
+

2022-01-28 14:04 UTC, LanaLem commented on src/sass/base/_container.scss
> -      max-width: 1024px;
+

2022-01-28 14:04 UTC, LanaLem commented on src/index.html
> +
+

2022-01-28 14:05 UTC, LanaLem commented on src/sass/utils/_fonts.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap');
удалила файл

2022-01-28 14:05 UTC, LanaLem commented on src/sass/main.scss
> +@import './layout/footer';
+исправила

2022-01-28 14:06 UTC, LanaLem commented on src/sass/components/_films-gallery.scss
> +  grid-row-gap: 20px;
это для самой сетки гридов, тут так надо)

2022-01-28 14:06 UTC, LanaLem commented on src/sass/components/_films-gallery.scss
> +    grid-row-gap: 30px;
+исправила

2022-01-28 14:06 UTC, LanaLem commented on src/sass/components/_films-gallery.scss
> +  padding: 20px 20px 120px;
+исправила

2022-01-28 14:06 UTC, LanaLem commented on src/sass/components/_films-gallery.scss
> +    padding: 60px 75px 150px;
+исправила

2022-01-28 14:06 UTC, LanaLem commented on src/sass/components/_films-gallery.scss
> +  @media screen and (min-width: 1024px) {
убрала

2022-01-28 14:06 UTC, LanaLem commented on src/sass/components/_film-card.scss
> +  height: 440px;
это высота карточки же, не постера

2022-01-28 14:07 UTC, LanaLem commented on src/sass/components/_film-card.scss
> +  max-width: 280px;
не красиво выглядит, если так сделать

2022-01-28 14:11 UTC, LanaLem commented
вроде все поправила

2022-01-28 14:37 UTC, Oleksandr-Stepanyshyn requested changes

2022-01-28 14:37 UTC, Oleksandr-Stepanyshyn commented on src/sass/base/_container.scss
> +    min-width: 768px;
тут max-width:768px;

2022-01-28 14:37 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_film-card.scss
>    font-weight: 500;
повторяются стили текста

2022-01-28 14:37 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_film-card.scss
>  .film-card__title {
повторяются стили текста

2022-01-28 14:37 UTC, Oleksandr-Stepanyshyn commented on src/sass/components/_films-gallery.scss
> +  grid-row-gap: 20px;
ок

2022-01-28 14:37 UTC, Oleksandr-Stepanyshyn commented
нужно перезалить в дев

2022-01-28 19:04 UTC, LanaLem commented on src/sass/base/_container.scss
> +    width: 1024px;
странно, что не отображается, я вроде уже добавляла эти паддинги: https://prnt.sc/26kxcm1

2022-01-28 19:05 UTC, LanaLem commented on src/sass/base/_container.scss
> +    min-width: 768px;
+исправила

2022-01-28 22:09 UTC, LanaLem commented on src/sass/components/_film-card.scss
>  .film-card__title {
сделала миксин

2022-01-28 22:09 UTC, LanaLem commented on src/sass/components/_film-card.scss
>    font-weight: 500;
сделала миксин

2022-01-28 22:10 UTC, LanaLem commented on src/sass/base/_container.scss
> +    min-width: 768px;
сорри, поправила

2022-01-28 22:11 UTC, LanaLem commented
вроде нашла как поменять ветку https://prnt.sc/26l09uv, посмотри, пожалуйста, все ли корректно?

и нету ли конфликтов. если есть, то завтра все-таки перепишу все новой веткой, а не в этой

2022-01-29 09:49 UTC, Oleksandr-Stepanyshyn approved these changes

2022-01-29 10:04 UTC, merged